name: Node CI

on: [push]
env:
  FORCE_COLOR: 2
jobs:
  test:
    name: v${{ matrix.node }} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [14.x, 16.x, 18.x]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - name: Build and run tests
      run: |
        npm run build --if-present
        npm test
